C#/CSEducation/Authorization.Users.API/Controllers/SiteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace Authorization.Users.API.Controllers
{
    [Route("[controller]")]
    public class SiteController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SiteController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [Route("[action]")]
        public IActionResult Index()
        {
            return View();
        }


        [Route("[action]")]
        public async Task<IActionResult> GetOrdersAsync()
        {
            //ViewBag.Message = "Test";

            var ordersClient = _httpClientFactory.CreateClient();

            var response = await ordersClient.GetAsync("https://localhost:5001/site/secret");

            var message = await response.Content.ReadAsStringAsync();

            ViewBag.Message = message;

            return View();
        }

    }
}

C#/CSEducation/Authorization.Users.API/Views/Shared/_Menu.cshtml
<a asp-controller="Site" asp-action="Index">Index</a>
<a asp-controller="Site" asp-action="GetOrders">GetOrders</a>

C#/CSEducation/Authorization.Users.API/Views/Site/GetOrders.cshtml
<h1>Index</h1>

<partial name="_Menu" />

@if(!string.IsNullOrEmpty(ViewData["Message"].ToString()))
{
	<p>
		@ViewData["Message"]
	</p>
}

C#/CSEducation/Authorization.Users.API/Views/Site/Index.cshtml
<h1>Index</h1>

<partial name="_Menu" />